export const STRIPE_PLANS = {
  basic: {
    name: "Basic",
    productId: "prod_UTq2riRVHklVk3",
    yearlyProductId: "prod_UTq2g2ruuNr4y9",
    monthlyPriceId: "price_1TUsM4Q4x6wAFY5tOYNKLnG0",
    yearlyPriceId: "price_1TUsM5Q4x6wAFY5tfct1eL74",
    monthlyPrice: 7,
    yearlyPrice: 70,
    aiCredits: 1000,
    features: [
      "Link 1 channel",
      "View basic analytics",
      "50 keywords/day",
      "5 topic suggestions/day",
      "AI analysis weekly",
      "SEO Analyzer (20 credits/query)",
      "Text to Video (30 credits/10 sec)",
      "Competitor analysis weekly",
      "Growth tasks & milestones",
      "1,000 AI Credits/month",
    ],
  },
  pro: {
    name: "Pro",
    productId: "prod_UTq2L9axVoCNVT",
    yearlyProductId: "prod_UTq2yO6239H9xb",
    monthlyPriceId: "price_1TUsM9Q4x6wAFY5towXlX4tu",
    yearlyPriceId: "price_1TUsMAQ4x6wAFY5taKuS7VAx",
    monthlyPrice: 15,
    yearlyPrice: 120,
    aiCredits: 10000,
    features: [
      "Link up to 3 channels",
      "Advanced analytics",
      "150 keywords/day",
      "10 topic suggestions/day",
      "AI analysis weekly",
      "SEO Analyzer (20 credits/query)",
      "Text to Video (30 credits/10 sec)",
      "Competitor analysis weekly",
      "AI Script Writer",
      "Text to Speech",
      "Voice Clone",
      "5 thumbnails/day",
      "YouTube Strategist AI",
      "Growth tasks & milestones",
      "10,000 AI Credits/month",
    ],
  },
  advanced: {
    name: "Advanced",
    productId: "prod_UTq2g47nqmWZWE",
    yearlyProductId: "prod_UTq2R7RKqTgc28",
    monthlyPriceId: "price_1TUsMCQ4x6wAFY5tn82m7eR6",
    yearlyPriceId: "price_1TUsMDQ4x6wAFY5tbzUMniBJ",
    monthlyPrice: 25,
    yearlyPrice: 230,
    aiCredits: 25000,
    features: [
      "Link up to 10 channels",
      "Advanced analytics",
      "Unlimited keywords",
      "20 topic suggestions/day",
      "Unlimited AI analysis",
      "SEO Analyzer (20 credits/query)",
      "Text to Video (30 credits/10 sec)",
      "Daily competitor analysis",
      "AI Script Writer",
      "Text to Speech",
      "Voice Clone",
      "Unlimited thumbnails",
      "YouTube Strategist AI",
      "Growth tasks & milestones",
      "25,000 AI Credits/month",
    ],
  },
} as const;

export type StripePlanKey = keyof typeof STRIPE_PLANS;
