export const STRIPE_PLANS = {
  basic: {
    name: "Basic",
    priceId: "price_1SmHf4IvqpEim8WgtxTKqyp0",
    productId: "prod_TjlB0qtrN0s4u6",
    monthlyPrice: 7,
    yearlyPrice: 70,
    aiCredits: 1000,
    features: [
      "Link 1 channel",
      "View Analytics",
      "50 Keywords/day",
      "5 Topics/day",
      "Weekly Channel Analysis",
      "Weekly Competitor Analysis",
      "1,000 AI Strategist Credits",
      "Basic Growth Tasks & Milestones",
    ],
  },
  pro: {
    name: "Pro",
    priceId: "price_1SmHfXIvqpEim8Wg9JtMKO3J",
    productId: "prod_TjlBgvbmpocKMF",
    monthlyPrice: 15,
    yearlyPrice: 120,
    aiCredits: 10000,
    features: [
      "Link up to 3 channels",
      "Advanced Analytics",
      "150 Keywords/day",
      "10 Topics/day",
      "Script Writer",
      "5 Thumbnails/day",
      "Weekly Analysis",
      "10,000 AI Strategist Credits",
      "Pro Growth Tasks & Milestones",
    ],
  },
  advanced: {
    name: "Advanced",
    priceId: "price_1SmHfeIvqpEim8WgyUq2VpbB",
    productId: "prod_TjlCT4ijKq11hk",
    monthlyPrice: 25,
    yearlyPrice: 230,
    aiCredits: 25000,
    features: [
      "Link up to 10 channels",
      "Advanced Analytics",
      "Unlimited Keywords",
      "20 Topics/day",
      "Script Writer",
      "Unlimited Thumbnails",
      "YouTube Strategist",
      "Daily Competitor Analysis",
      "25,000 AI Strategist Credits",
      "Advanced Growth Tasks & Milestones",
    ],
  },
} as const;

export type StripePlanKey = keyof typeof STRIPE_PLANS;
