export const STRIPE_PLANS = {
  basic: {
    name: "Basic",
    productId: "prod_TjlB0qtrN0s4u6",
    monthlyPriceId: "price_1SmHf4IvqpEim8WgtxTKqyp0",
    monthlyPrice: 7,
    yearlyPrice: 70,
    aiCredits: 1000,
    features: [
      "Link 1 channel",
      "View basic analytics",
      "50 keywords/day",
      "5 topic suggestions/day",
      "AI analysis weekly",
      "Competitor analysis weekly",
      "Growth tasks & milestones",
      "1,000 AI Credits",
    ],
  },
  pro: {
    name: "Pro",
    productId: "prod_TjlBgvbmpocKMF",
    monthlyPriceId: "price_1SmHfXIvqpEim8Wg9JtMKO3J",
    monthlyPrice: 15,
    yearlyPrice: 120,
    aiCredits: 10000,
    features: [
      "Link up to 3 channels",
      "Advanced analytics",
      "150 keywords/day",
      "10 topic suggestions/day",
      "AI analysis weekly",
      "Competitor analysis weekly",
      "AI Script Writer",
      "5 thumbnails/day",
      "YouTube Strategist AI",
      "Growth tasks & milestones",
      "10,000 AI Credits",
    ],
  },
  advanced: {
    name: "Advanced",
    productId: "prod_TjlCT4ijKq11hk",
    monthlyPriceId: "price_1SmHfeIvqpEim8WgyUq2VpbB",
    monthlyPrice: 25,
    yearlyPrice: 230,
    aiCredits: 25000,
    features: [
      "Link up to 10 channels",
      "Advanced analytics",
      "Unlimited keywords",
      "20 topic suggestions/day",
      "Unlimited AI analysis",
      "Daily competitor analysis",
      "AI Script Writer",
      "Unlimited thumbnails",
      "YouTube Strategist AI",
      "Growth tasks & milestones",
      "25,000 AI Credits",
    ],
  },
} as const;

export type StripePlanKey = keyof typeof STRIPE_PLANS;
